config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'update_adoption'
    end
    collection do
      get 'search'
    end
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    
    resources :rooms, only: [:create, :show] do
      resources :messages, only: [:create]
    end
  end

  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
    resources :purchases, only: [:index, :create]
  end

  resources :users, only: [:show, :edit, :update, :destroy]
   
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_eight_header.html.erb
    <header class="site-header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo5.png", class: :header_logo), root_path %>
          </div>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "投稿する", new_item_path, class: :nav__link %>
             <%= link_to "もどる", items_path, class: :nav__link %>
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__auth %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__link %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
    <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_five_header.html.erb
    <header class="site-header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo5.png", class: :header_logo), root_path %>
          </div>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "出品する", new_item_path, class: :nav__link %>
             <%= link_to "もどる", root_path, class: :nav__link %>
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__auth %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__link %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_fourth-header.html.erb
  <header class="fourth-header">
    <%= link_to image_tag('logo4.png' , class:"fourth-logo"), "/" %>
  </header>

app/views/shared/_fourth_header.html.erb
  <header class="fourth-header">
    <%= link_to image_tag('logo4.png' , class:"fourth-logo"), "/" %>
  </header>

app/views/shared/_header.html.erb
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>

          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "投稿する", new_post_path, class: :nav__btn %>
              <%= link_to "購入する", destroy_user_session_path, class: :nav__btn %>
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo2.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_second_header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo2.png", class:"second-logo"), "/" %>
</header>

app/views/shared/_seven_header.html.erb
<header class='seven-header'>
  <%= link_to image_tag("logo7.png", class:"seven-logo"), "/" %>
</header>

app/views/shared/_six-header.html.erb
<header class='six-header'>
  <%= link_to image_tag("logo6.png", class:"six-logo"), "/" %>
</header>

app/views/shared/_third-header.html.erb
  <header class="posts-sell-header">
    <%= link_to image_tag('logo3.png' , class:"second-logo"), "/" %>
  </header>

app/views/shared/_third_header.html.erb
  <header class="posts-sell-header">
    <%= link_to image_tag('logo3.png' , class:"second-logo"), "/" %>
  </header>