config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'update_adoption'
    end
    collection do
      get 'search'
    end
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    
    resources :rooms, only: [:create, :show] do
      resources :messages, only: [:create]
    end
  end

  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
    resources :purchases, only: [:index, :create]
  end

  resources :users, only: [:show, :edit, :update, :destroy]
   
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  validate :acceptable_image

  with_options presence: true do
    validates :name, length: { maximum: 99 }
    validates :description, length: { maximum: 999 }
    validates :price
    validates :item_category_id, numericality: { only_integer: true, greater_than: 1, message: 'を入力してください' }
    validates :shipping_fee_id, numericality: { only_integer: true, greater_than: 1, message: 'を入力してください' }
    validates :shipping_days_id, numericality: { only_integer: true, greater_than: 1, message: 'を入力してください' }
    validates :user, presence: true
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name item_category_id price shipping_days_id favorites]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[user favorites item_category shipping_fee shipping_days]
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :item_category
  belongs_to_active_hash :shipping_fee
  belongs_to_active_hash :shipping_days

  belongs_to :user
  has_many :users, through: :favorites
  has_many :purchases, dependent: :destroy
  has_many :favorites, as: :favoritable, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  private

  def acceptable_image
    unless item_image.attached?
      errors.add(:item_image, 'を添付してください')
      return
    end

    errors.add(:item_image, 'は2MB以下でなければなりません') unless item_image.byte_size <= 2.megabyte

    acceptable_types = ['image/jpeg', 'image/png']
    return if acceptable_types.include?(item_image.content_type)

    errors.add(:item_image, 'はJPEGまたはPNG形式である必要があります')
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
    @items = Item.includes(:user).all
  end

  def show
    @item = Item.find(params[:id])
    @user = @item.user
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_purchases
    @item = Item.find(params[:id])
    @item.update(purchases: true)
    redirect_to @item, notice: '準備中です'
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  def search
    @q = Item.ransack(params[:q])
    @search_results = @q.result(distinct: true) if params[:q].present?
    @items = Item.all
    render :index
  end

  def favorite
  end

  private

  def set_post
    @item = Item.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def item_params
    params.require(:item).permit(:item_image, :name, :description, :price, :age, :item_category_id, :shipping_fee_id,
                                 :shipping_days_id).merge(user_id: current_user.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_favorite.html.erb
  <div id="favorite-btn<%= @item.id %>">
<% if user_signed_in? && @item.favorited_by?(current_user) %>
  <%= link_to "お気に入り解除", item_favorites_path(@item), data: { turbo_method: :delete }, class: "favorite-btn-active" %>
   <% else %>
  <%= link_to "お気に入り追加", item_favorites_path(@item), data: { turbo_method: :post }, class: "favorite-btn" %>
    <% end %>
  </div>

app/views/items/_item.html.erb
   <div class="card">
   <%= link_to (image_tag item.item_image, class: :card__img), item_path(item) %>

      <% if item.purchases.present? %>
        <div class="found-home-second">
          <span>完売しました</span>
        </div>
      <% end %>

<div class="card__body">
  <span class="card__title"><p>商品名：<%= link_to item.name, item_path(item)%></p></span>
  <span class="card__address"><p>カテゴリー：<%= link_to item.item_category.name, item_path(item) %></p></span>
</div>
</div>

app/views/items/edit.html.erb
<div class="edit__container">

<div class="posts-sell-contents">

  <%= render "shared/third_header" %>

  <div class="posts-sell-main">
    <h2 class="posts-sell-title">商品を登録してください</h2>

     <%= form_with model: @item, local: true do |f| %>
     <%= render 'shared/error_messages', model: @item %>

     <div class="items-description">

    <%# 商品の写真 %>
    <div class="img-upload">
      <div class="upload-container">
      <div class="weight-bold-text">
        写真を添付してください
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :item_image, id:"item_image" %>
      </div>
      <% if @item.persisted? && @item.item_image.attached? %>
      <%= image_tag @item.item_image, class: "item_image" %>
      <% end %>
    </div>
    </div>
    <%# /商品の写真 %>

     <%# 商品名 %>
    <div class="new-posts">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"posts-text", id:"name", placeholder:"(商品名を入力してください)", maxlength:"100" %>
      <%# 商品名 %>

       <%# 商品詳細 %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          商品詳細
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_area :description, class:"posts-text", id:"description", placeholder:"(商品の詳細を入力してください)", maxlength:"100" %>
      </div>
      <%# 商品詳細 %>

       <%# 商品カテゴリー %>
      <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:item_category_id, ItemCategory.all, :id, :name, {}, {class:"select-box", id:"item_category"}) %>
      <%# 商品カテゴリー %>
    </div>

    <%# 配送について %>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_id, ShippingFee.all, :id, :name, {}, {class:"select-box", id:"shipping_fee"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_days_id, ShippingDays.all, :id, :name, {}, {class:"select-box", id:"shipping_days"}) %>
      </div>
    </div>
    </div>
    <%# /配送について %>


    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
    </div>
    <%# /下部ボタン %>
    </div>
      <% end %>

</div>

app/views/items/index.html.erb
<div class="item__container">
<%= render "shared/five_header" %>

<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <h2 class="page-title">こんにちは
        <%= link_to "#{current_user.nickname} さん", user_path(current_user), class: :login__link%></h2>
        <p>こちらでは動物に関する様々なアイテムを購入いただけます</p>
        <p>お好みのアイテムをお選びください</p>
      </div>
    <% end %>

     <!-- 通常の投稿を上部にのみ表示 -->
    <div class="card__wrapper">
      <%= render partial: 'item', collection: @items, as: :item %>
    </div>
    </div>
  </main>


   <div class="search-page">
  <h3> 🐈‍⬛ 検索ページ 🔍</h3>
   </div>

   <div class='item-contents' id="detailed-search-result-wrapper">
   <%= search_form_for @q, url: search_items_path, html: { id: "detailed-search-form" } do |f| %>

   <div class="search-field">
   <%= f.label :item_category_cont, '【 カテゴリー 】' %><p>
   <%= f.collection_check_boxes :item_category_id_in, ItemCategory.where.not(name: '---'), :id, :name %></p>
   </div>

  <div class="search-field">
   <%= f.label :address_cont, '【 発送までの日数 】' %><p>
   <%= f.collection_check_boxes :shipping_days_id_in, ShippingDays.where.not(name: '---'), :id, :name %></p>
   </div>

   <div class="search-field">
      <%= f.label :price_gteq, '【 価格 】'%>
      <br>
      <%= f.number_field :price_gteq %> 円以上
      <br>
      <%= f.number_field :price_lteq %> 円以下
   </div>

   <div class="search-field">
   <%= f.submit '検索' %>
   </div>
   <% end %>
   </div>

<ul>
  <% filtered_items = @search_results.present? ? @search_results.reject { |item| item.purchases.present? } : [] %>
  <% if filtered_items.any? %>
    <% filtered_items.each do |item| %>
      <li class="list">
        <div class="posted-content">
          <%= link_to (image_tag item.item_image, class: :card__img), item_path(item) %>

          <% if item.purchases.present? %>
            <div class="found-home-second">
              <span>準備中です</span>
            </div>
          <% end %>

          <div class="card__body">
            <span class="card__title"><p>商品名：<%= link_to item.name, item_path(item)%></p></span>
            <span class="card__address"><p>カテゴリー：<%= link_to item.item_category.name, item_path(item) %></p></span>
          </div>
        </div>
      </li>
    <% end %>
  <% else %>
    <p class="no-results-msg">該当する商品はありませんでした</p>
  <% end %>
</ul>

        <footer class="footer">
      <p class="copyright">Copyright © Find a family All rights reserved.</p>
    </footer>
</div>

app/views/items/new.html.erb
<div class="new__container">
<div class="posts-sell-contents">

  <%= render "shared/third_header" %>

  <div class="posts-sell-main">
    <h2 class="posts-sell-title">商品を登録してください</h2>

     <%= form_with model: @item, local: true do |f| %>
     <%= render 'shared/error_messages', model: @item %>

     <div class="items-description">

    <%# 商品の写真 %>
    <div class="img-upload">
      <div class="upload-container">
      <div class="weight-bold-text">
        写真を添付してください
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :item_image, id:"item_image" %>
      </div>
      <% if @item.persisted? && @item.item_image.attached? %>
      <%= image_tag @item.item_image, class: "item_image" %>
      <% end %>
    </div>
    </div>
    <%# /商品の写真 %>

     <%# 商品名 %>
    <div class="new-posts">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"posts-text", id:"name", placeholder:"(商品名を入力してください)", maxlength:"100" %>
      <%# 商品名 %>

       <%# 商品詳細 %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          商品詳細
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_area :description, class:"posts-text", id:"description", placeholder:"(商品の詳細を入力してください。 実際に使用して、こういう所が良かったなど、体験談があればぜひ入力してください)", maxlength:"1000" %>
      </div>
      <%# 商品詳細 %>

       <%# 商品カテゴリー %>
      <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:item_category_id, ItemCategory.all, :id, :name, {}, {class:"select-box", id:"item_category"}) %>
      <%# 商品カテゴリー %>
    </div>

    <%# 配送について %>
    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_fee_id, ShippingFee.all, :id, :name, {}, {class:"select-box", id:"shipping_fee"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_days_id, ShippingDays.all, :id, :name, {}, {class:"select-box", id:"shipping_days"}) %>
      </div>
    </div>
    </div>
    <%# /配送について %>


    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格</span>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
    </div>
    <%# /下部ボタン %>
    </div>
      <% end %>
</div>
</div>

app/views/items/show.html.erb
<div class="show__container">
<%= render "shared/eight_header" %>

  <div class="post-show">
  <div class="post-box">
    <h2 class="title_name">
      <%= @item.name %>
    </h2>

    <%= render partial: "items/favorite", locals: { item: @item } %>

    <div class="post-img-content">
      <%= link_to image_tag @item.item_image, class: "item-box-img" %>

          <% if @item.purchases.present? %>
          <div class='found-home'>
            <span>完売しました</span>
          </div>
          <% end %>

      <div class="post-explain-box">
      </div>

      <table class="detail-table">
        <tbody>

            <tr>
            <th class="detail-post">出品者</th>
            <td class="detail-value"><%= @user.nickname %></td>
          </tr>


          <tr>
            <th class="detail-post">商品名</th>
            <td class="detail-value"><%= @item.name %></td>
          </tr>

          <tr>
            <th class="detail-post">商品詳細</th>
            <td class="detail-value"><%= @item.description %></td>
          </tr>

          <tr>
            <th class="detail-post">カテゴリー</th>
            <td class="detail-value"><%= @item.item_category.name %></td>
          </tr>
          
          <tr>
            <th class="detail-post">配送料の負担</th>
            <td class="detail-value"><%= @item.shipping_fee.name %></td>
          </tr>
          
          <tr>
            <th class="detail-post">発送日数</th>
            <td class="detail-value"><%= @item.shipping_days.name %></td>
          </tr>

          <tr>
            <th class="detail-post">販売価格</th>
            <td class="detail-value"><%= @item.price %>円</td>
          </tr>
        </tbody>
      </table>

<% if user_signed_in? %>
<!-- 完売しており、出品者以外のユーザーが商品ページを見ている場合 -->
   <% if @item.purchases.present? && current_user != @item.user %>
    <%= link_to 'TOPページに戻る', items_path, class: "back-to-top-btn" %>

    <!-- 購入済みの商品ページの場合 -->
    <% elsif @item.purchases.present? && current_user == @item.user %>
    <div class="actions">
      <%= link_to "削除する", item_path(@item), data: { turbo_method: :delete }, class: "back-to-top-btn delete-btn" %>
    </div>
    <!-- 出品者が自分の商品ページを見ている場合 -->
  <% elsif current_user == @item.user %>
    <div class="edit-delete-buttons">
      <%= link_to "投稿を編集する", edit_item_path(@item), class: "post-red-btn" %>
      <%= link_to "削除する", item_path(@item), data: { turbo_method: :delete }, class: "post-destroy" %>
    </div>
  <% else %>
    <!-- 出品者以外のユーザーがまだ購入していない商品ページを見ている場合 -->
    <div class="item-buy-buttons">
      <%= link_to "購入画面に進む", item_purchases_path(@item), data: { turbo: false }, class: "post-buy-btn" %>
    </div>
  <% end %>
<% end %>
    </div>
</div>
</div>
</div>