config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'update_adoption'
    end
    collection do
      get 'search'
    end
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    
    resources :rooms, only: [:create, :show] do
      resources :messages, only: [:create]
    end
  end

  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
    resources :purchases, only: [:index, :create]
  end

  resources :users, only: [:show, :edit, :update, :destroy]
   
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :category
  belongs_to_active_hash :gender
  belongs_to :user
  # has_many :rooms, dependent: :nullify
  has_many :comments, dependent: :destroy
  has_many :users, through: :favorites
  has_many :favorites, as: :favoritable, dependent: :destroy
  has_one_attached :animal_image

  def self.ransackable_attributes(auth_object = nil)
    %w[title category_id animal_type gender_id address favorites]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[user category gender favorites]
  end

  with_options presence: true do
    validates :title, length: { maximum: 99 }
    validates :category_id, numericality: { only_integer: true, greater_than: 1, message: 'を入力してください' }
    validates :animal_type, length: { maximum: 39 }
    validates :gender_id, numericality: { only_integer: true, greater_than: 1, message: 'を入力してください' }
    validates :personality, length: { maximum: 99 }
    validates :description, length: { maximum: 1999 }
    validates :user, presence: true
    validates :address, length: { maximum: 99 }
  end

  validate :acceptable_image

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  private

  def acceptable_image
    unless animal_image.attached?
      errors.add(:animal_image, 'を添付してください')
      return
    end

    errors.add(:animal_image, 'は2MB以下でなければなりません') if animal_image.byte_size > 2.megabytes

    acceptable_types = ['image/jpeg', 'image/png']
    return if acceptable_types.include?(animal_image.content_type)

    errors.add(:animal_image, 'はJPEGまたはPNG形式である必要があります')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :update_adoption, :favorite]

  def index
    @q = Post.ransack(params[:q])
    @posts = Post.all
    @posts = Post.includes(:user).all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @room = (Room.find_or_create_by(post_id: @post.id, user_id: current_user.id) if user_signed_in?)
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_adoption
    @post = Post.find(params[:id])
    @post.update(adoption: true)
    redirect_to @post, notice: '家族が見つかりました！'
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def favorite
  end

  def search
    @q = Post.ransack(params[:q])
    @search_results = @q.result(distinct: true) if params[:q].present?
    @posts = Post.all
    render :index
  end

  private

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:animal_image, :title, :category_id, :animal_type, :age, :gender_id, :personality,
                                 :description, :address).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_favorite.html.erb
<div id="favorite-btn<%= @post.id %>">
<% if user_signed_in? && @post.favorited_by?(current_user) %>
  <%= link_to "お気に入り解除", post_favorites_path(@post), data: { turbo_method: :delete }, class: "favorite-btn-active" %>
   <% else %>
  <%= link_to "お気に入り追加", post_favorites_path(@post), data: { turbo_method: :post }, class: "favorite-btn" %>
    <% end %>
    </div>

app/views/posts/_post.html.erb
    <div class="card">
      <%= link_to (image_tag post.animal_image, class: :card__img), post_path(post) %>

      <% if post.adoption.present? %>
        <div class="found-home-second">
          <span>見つかりました</span>
        </div>
      <% end %>

      <div class="card__body">
        <%= link_to post.title, post_path(post), class: :card__title %>
        <span class="card__address"><p>場所：<%= link_to post.address, post_path(post), class: :card__address %></p></span>
        <%= link_to " #{post.user.nickname}さん", user_path(post.user), class: :card__user %>
      </div>
    </div>

app/views/posts/edit.html.erb
<div class="edit__container">
<div class="posts-sell-contents">

  <%= render "shared/third_header" %>

  <div class="posts-sell-main">
    <h2 class="posts-sell-title">🐈‍⬛動物について教えてください🐩</h2>

     <%= form_with model: @post, local: true do |f| %>
     <%= render 'shared/error_messages', model: @post %>


    <%# 動物の写真 %>
    <div class="img-upload">
      <div class="upload-container">
      <div class="weight-bold-text">
        🐈‍⬛写真を添付してください
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :animal_image, id:"animal-image" %>
      </div>
      <% if @post.animal_image.attached? %>
      <%= image_tag @post.animal_image, class: "animal-image" %>
      <% end %>
    </div>
    </div>
    <%# /動物の写真 %>

     <%# タイトル %>
    <div class="new-posts">
      <div class="weight-bold-text">
        🐈‍⬛タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"posts-text", id:"title", placeholder:"(例:飼い犬が迷子になってしまいました、猫を保護しましたなど)", maxlength:"100" %>
      <%# タイトル %>

       <%# 動物のカテゴリー %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          🐈‍⬛カテゴリーを選んでください
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
      </div>
      <%# 動物のカテゴリー %>

      <%# 動物の種類 %>
        <div class="weight-bold-text">
          🐈‍⬛種類を教えてください
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_area :animal_type, class:"posts-text", id:"animal_type", placeholder:"(例:猫、犬、鳥など)", maxlength:"40" %>
        <%# 動物の種類 %>

        <%# 動物の年齢 %>
        <div class="weight-bold-text">
          🐈‍⬛年齢を教えてください
        </div>
        <%= f.text_area :age, class:"posts-text", id:"age", placeholder:"(例:3ヶ月、2歳、不明など)" %>
       <%# 動物の年齢 %>


       <%# 動物の性別 %>
      <div class="weight-bold-text">
          🐈‍⬛性別を教えてください
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"gender"}) %>
      <%# 動物の性別 %>

      <%# 動物の性格 %>
      <div class="weight-bold-text">
        🐈‍⬛性格を教えてください
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :personality, class:"posts-text", id:"personality", placeholder:"(例:人馴れしていません、人懐っこいですなど)", maxlength:"100" %>
      <%# 動物の性格 %>

      <%# 場所 %>
      <div class="weight-bold-text">
        🐈‍⬛保護や譲渡の場所を教えてください
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :address, class:"posts-text", id:"address", placeholder:"(例:東京都板橋区〜)", maxlength:"100" %>
      <%# 場所 %>

      <%# 動物の詳細 %>
      <div class="weight-bold-text">
        🐈‍⬛その他の詳細を入力してください
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :description, class:"content-text", id:"description", placeholder:"(例:昨日の夜、脱走してしまいました。三毛猫とサビ猫のMIXです。首輪はしていません。外に出たことがない為、すごく心配しています。東京都板橋区⚪︎⚪︎あたりで見かけた方はご連絡いただけますと幸いです。)

(例:ペットのゴールデンレトリバーが赤ちゃんを産みました！5匹いてとても可愛いです。里親さんを探しています。ご希望の方はご連絡ください！)", maxlength:"2000" %>
      <%# 動物の性格 %>


    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" , class:"btn-edit" %>
      <% if user_signed_in? && current_user == @post.user && @post.adoption.nil? %>
      <%=link_to '見つかりました！', update_adoption_post_path(@post), method: :get, class:"adoption-btn" %>
      <% end %>
    </div>
    <%# 下部ボタン %>
     <% end %>
  </div>
</div>
</div>

app/views/posts/index.html.erb
<div class="post__container">
<%= render "shared/header" %>

<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <h2 class="page-title">こんにちは
        <%= link_to "#{current_user.nickname} さん", user_path(current_user), class: :login__link %></h2>
      </div>
    <% end %>

    <!-- 通常の投稿を上部にのみ表示 -->
    <div class="card__wrapper">
      <%= render partial: 'post', collection: @posts, as: :post %>
    </div>
  </div>
</main>

<% if user_signed_in? %>
<!-- 検索フォームの表示 -->
<div class="search-page">
  <h3> 🐈‍⬛ 検索ページ 🔍</h3>
</div>

<div class='item-contents' id="detailed-search-result-wrapper">
  <%= search_form_for @q, url: search_posts_path, html: { id: "detailed-search-form" } do |f| %>

    <div class="search-field">
      <%= f.label :category_id_in, '【 カテゴリー 】' %><p>
      <%= f.collection_check_boxes :category_id_in, Category.where.not(name: '---'), :id, :name %></p>
    </div>

    <div class="search-field">
      <%= f.label :animal_type_cont, '【 動物の種類 】' %>
      <%= f.text_field :animal_type_cont, placeholder: '種類', value: params[:q]&.dig(:animal_type_cont) %>
    </div>

    <div class="search-field">
      <%= f.label :gender_id_in, '【 性別 】' %><p>
      <%= f.collection_check_boxes :gender_id_in, Gender.where.not(name: '---'), :id, :name %></p>
    </div>

    <div class="search-field">
      <%= f.label :address_cont, '【 保護や譲渡の場所 】' %>
      <%= f.text_field :address_cont, placeholder: '保護や譲渡の場所', value: params[:q]&.dig(:address_cont) %>
    </div>

    <div class="search-field">
      <%= f.submit '検索' %>
    </div>
  <% end %>
</div>

<!-- 検索結果があれば表示 -->
<% if @search_results.present? %>
  <div class="search-results">
    <h3>検索結果</h3>
  </div>
    <ul>
      <% @search_results.reject { |post| post.adoption.present? }.each do |post| %>
        <li class="list">
          <div class="posted-content">
      <%= link_to (image_tag post.animal_image, class: :card__img), post_path(post) %>

      <% if post.adoption.present? %>
        <div class="found-home-second">
          <span>見つかりました</span>
        </div>
      <% end %>

      <div class="card__body">
        <%= link_to post.title, post_path(post), class: :card__title %>
        <span class="card__address"><p>場所：<%= link_to post.address, post_path(post), class: :card__address %></p></span>
        <%= link_to " #{post.user.nickname}さん", post_path(post), class: :card__user %>
      </div>
          </div>
        </li>
      <% end %>
      <% else %>
        <p class="no-results-msg">該当する投稿はありませんでした</p>
    </ul>
<% end %>
<% end %>

<footer class="footer">
  <p class="copyright">Copyright © Find a family All rights reserved.</p>
</footer>
</div>

app/views/posts/new.html.erb
<div class="new__container">
<div class="posts-sell-contents">
<%= render "shared/third_header" %>

  <div class="posts-sell-main">
    <h2 class="posts-sell-title">🐈‍⬛動物について教えてください🐩</h2>

     <%= form_with model: @post, local: true do |f| %>
     <%= render 'shared/error_messages', model: @post %>


    <%# 動物の写真 %>
    <div class="img-upload">
      <div class="upload-container">
      <div class="weight-bold-text">
        🐈‍⬛写真を添付してください
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :animal_image, id:"animal-image" %>
      </div>
      <% if @post.animal_image.attached? %>
      <%= image_tag @post.animal_image, class: "animal_image" %>
      <% end %>
    </div>
    </div>
    <%# /動物の写真 %>

     <%# タイトル %>
    <div class="new-posts">
      <div class="weight-bold-text">
        🐈‍⬛タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"posts-text", id:"title", placeholder:"(例:飼い犬が迷子になってしまいました、猫を保護しましたなど)", maxlength:"100" %>
      <%# タイトル %>

       <%# 動物のカテゴリー %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          🐈‍⬛カテゴリーを選んでください
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
      </div>
      <%# 動物のカテゴリー %>

      <%# 動物の種類 %>
        <div class="weight-bold-text">
          🐈‍⬛種類を教えてください
          <span class="indispensable">必須</span>
        </div>
         <%= f.text_area :animal_type, class:"posts-text", id:"animal_type", placeholder:"(例:猫、犬、鳥など)", maxlength:"40" %>
        <%# 動物の種類 %>

        <%# 動物の年齢 %>
        <div class="weight-bold-text">
          🐈‍⬛年齢を教えてください
        </div>
        <%= f.text_area :age, class:"posts-text", id:"age", placeholder:"(例:3ヶ月、2歳、不明など)" %>
       <%# 動物の年齢 %>


       <%# 動物の性別 %>
      <div class="weight-bold-text">
          🐈‍⬛性別を教えてください
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"select-box", id:"gender"}) %>
      <%# 動物の性別 %>

      <%# 動物の性格 %>
      <div class="weight-bold-text">
        🐈‍⬛性格を教えてください
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :personality, class:"posts-text", id:"personality", placeholder:"(例:人馴れしていません、人懐っこいですなど)", maxlength:"100" %>
      <%# 動物の性格 %>

      <%# 場所 %>
      <div class="weight-bold-text">
        🐈‍⬛保護や譲渡の場所を教えてください
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :address, class:"posts-text", id:"address", placeholder:"(例:東京都板橋区〜)", maxlength:"100" %>
      <%# 場所 %>

      <%# 動物の詳細 %>
      <div class="weight-bold-text">
        🐈‍⬛その他の詳細を入力してください
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :description, class:"content-text", id:"description", placeholder:"(例:昨日の夜、脱走してしまいました。三毛猫とサビ猫のMIXです。首輪はしていません。外に出たことがない為、すごく心配しています。東京都板橋区⚪︎⚪︎あたりで見かけた方はご連絡いただけますと幸いです。)

(例:ペットのゴールデンレトリバーが赤ちゃんを産みました！5匹いてとても可愛いです。里親さんを探しています。ご希望の方はご連絡ください！)", maxlength:"2000" %>
      <%# 動物の性格 %>


    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
    </div>
    <%# /下部ボタン %>
    </div>
      <% end %>
</div>
</div>

app/views/posts/show.html.erb
<div class="show__container">
 <%= render "shared/fourth_header" %>

  <div class="post-show">
  <div class="post-box">
    <h2 class="title_name">
      <%= @post.title %>
    </h2>

  <%= render partial: "posts/favorite", locals: { post: @post } %>

    <div class="post-img-content">
      <%= link_to image_tag @post.animal_image, class: "item-box-img" %>

      <% if @post.adoption.present? %>
        <div class="found-home">
          <span>見つかりました</span>
        </div>
      <% end %>

      <div class="post-explain-box">
      </div>

      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-post">投稿者</th>
            <td class="detail-value">
                <%= @post.user.nickname %>
              </td>
          </tr>
          <tr>
            <th class="detail-post">タイトル</th>
            <td class="detail-value"><%= @post.title %></td>
          </tr>
          <tr>
            <th class="detail-post">カテゴリー</th>
            <td class="detail-value"><%= @post.category.name %></td>
          </tr>
          <tr>
            <th class="detail-post">種類</th>
            <td class="detail-value"><%= @post.animal_type %></td>
          </tr>
          <tr>
            <th class="detail-post">年齢</th>
            <td class="detail-value"><%= @post.age %></td>
          </tr>

          <tr>
            <th class="detail-post">性別</th>
            <td class="detail-value"><%= @post.gender.name %></td>
          </tr>

          <tr>
            <th class="detail-post">性格</th>
            <td class="detail-value"><%= @post.personality %></td>
          </tr>

          <tr>
            <th class="detail-post">保護や譲渡の場所</th>
            <td class="detail-value"><%= @post.address %></td>
          </tr>

          <tr>
            <th class="detail-post">詳細情報</th>
            <td class="detail-value"><%= @post.description %></td>
          </tr>
        </tbody>
      </table>

      <% if @post.adoption.present? && current_user == @post.user %>
          <%= link_to "削除する", post_path(@post), data: { turbo_method: :delete }, class: "back-to-top-btn delete-btn" %>
          <% end %>


      <% if user_signed_in? %>
        <% unless @post.adoption.present? %>
          <% if current_user == @post.user %>
            <div class="edit-delete-buttons">
              <%= link_to "投稿を編集する", edit_post_path(@post), method: :get, class: "post-red-btn" %>
              <%= link_to "削除する", post_path(@post), data: { turbo_method: :delete }, class: "post-destroy" %>
              <%=link_to 'チャットルームへ', post_room_path(@room.post, @room), class:"back-second-btn" %>
            </div>
          <% end %>
        <% end %>
      <% end %>

  <div class="comment-box">
    <% if user_signed_in? && current_user != @post.user && @post.adoption.blank? %> 
    <%= form_with model: [@post, @comment], local: true do |f| %>

      <%= render 'shared/error_messages', model: @comment %>

      <div class="field">
        <%= f.label :content, "[ コメント ]", class: "comment-container" %><br />
        <div class="comments_lists">
    <% @comments.each do |comment| %>
      <div class="comments_list">
        <% if comment.comment_image.attached? %>
          <%= image_tag comment.comment_image, class: "comment_image" %>
        <% end %>
        <div class="comment-content">
         <%= comment.content %>
        <%= link_to "（#{comment.user.nickname}）", user_path(comment.user), class: :comment_user %>
        </div>
        </div>
    <% end %>
     </div>
        <%= f.text_area :content, class: "comment-text" %>
        <p class="comment-warn">
          相手のことを考え丁寧なコメントを心がけましょう。
        </p>
      </div>
      <div class="click-upload">
        <%= f.file_field :comment_image, id: "comment-image" %>
      </div>
      <div class="actions">
        <%= f.submit "コメントを送信する", class: "comment-btn" %>
        <%= link_to "#{@post.user.nickname}さんへ連絡", post_room_path(@room.post, @room), class: "dm-btn" %>
      </div>
    <% end %>
  <% end %>
</div>